VG-10 Mission page
x-team/vetting-games-api pull request #3
Opened 2022-12-02 14:44 UTC by Arthaclarius

## Tickets

https://x-team-internal.atlassian.net/browse/VG-10

## Demo

[![image](https://user-images.githubusercontent.com/31192466/205316452-80408c02-d9be-475f-9c07-271720b3b3b5.png)](https://vimeo.com/777364079/219f661a31)

## Description

### DB Changes

- Added release date to the Mission table
- Removed the finished column from the Game table. It was unnecessary.
- Updated the Seed function to add 3 missions

### Error handling

Added a folder with error classes to have more consistency while throwing errors. Updated the resolvers to use these new classes.

### Date Scalar

Added a scalar to handle dates

### `startGame` Resolver

When starting a game, it will check if there is already a game running. If so, it throws an error.

2022-12-05 14:11 UTC, lucasiervolino commented on prisma/schema.prisma
> +  releaseDate DateTime?
Is it intended that `releaseDate` has an optional value? Just to make sure.

2022-12-05 19:58 UTC, smaryka requested changes
Just need to resolve the use of `releaseDate`

2022-12-05 19:58 UTC, smaryka commented on prisma/schema.prisma
> +  releaseDate DateTime?
It might make sense for this to be required, and compare to current time to determine which missions are released.

2022-12-07 20:01 UTC, Arthaclarius commented
> 

Little confused there. I left that column as optional in case a mission does not have a planned release date. Eventually, a release date can be an incoming date in case we want to release it on a specific date in the future. Could you provide me an example of a Mission that is not released?

2022-12-13 20:42 UTC, Arthaclarius commented
> 



> > It might make sense for this to be required, and compare to current time to determine which missions are released.
> 
> Little confused there. I left that column as optional in case a mission does not have a planned release date. Eventually, a release date can be an incoming date in case we want to release it on a specific date in the future. Could you provide me an example of a Mission that is not released?
> 
> @smaryka @lucasiervolino

For example, Mission 1 is already released and is available to the public, but missions 2 and 3 are not ready yet and do not have a planned date for their release, probably until the missions are coded and tested.

2022-12-13 21:45 UTC, smaryka approved these changes
I am fine with leaving the release date optional, and keep our options open. I'm not sure we will want to present unreleased missions to the user anyways, but that is a decision that can be taken later,

2022-12-13 21:53 UTC, merged